version: '3.7'

services:

  # Configure a container that pulls in our current code
  int-test-example:
    image: node:10-alpine
    depends_on:
      - redis
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    user: node
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - default
    command: npm start

  redis:
    image: redis:4-alpine
    networks:
      - default

  # A target for running both unit and integration tests
  test-all:
    image: node:10-alpine
    depends_on:
      - redis
      - int-test-example
    environment:
      - NODE_ENV=test
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: npm run test:all

  # A target for running only integration tests
  test-integration:
    image: node:10-alpine
    depends_on:
      - redis
      - int-test-example
    environment:
      - NODE_ENV=test
    volumes:
      - .:/opt/app
    working_dir: /opt/app
    command: npm run test:integration